services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: react-frontend
    env: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: build
    plan: free
